repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    -   id: flake8
        args: ["--ignore","E501"]

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    -   id: bandit
        exclude: ^src/test/
        args: ["-lll"]
