version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.17

orbs:
  gh: circleci/github-cli@1.0
  lumigo-orb: lumigo/lumigo-orb@volatile

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
  test:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: go install golang.org/dl/go1.16@latest
    - run: go1.16 download
    - run: go install golang.org/dl/go1.18@latest
    - run: go1.18 download
    - run: export GO=go && make checks # runs test for go1.17
    - run: export GO=go1.16 && make checks
    - run: export GO=go1.18 && make checks
    - run: make upload-codecov
    - *save_cache
  
  create-push-release:
    executor:
      name: default
    steps:
    - gh/setup
    - checkout
    - run: |
        make release 

workflows:
  ci-build:
    jobs:
    - test:
        filters:
          branches:
            ignore: master
    - lumigo-orb/be-deploy:
        filters:
          branches:
            ignore: master
        requires:
          - test
    - lumigo-orb/integration-test:
        deploy_spec: default
        tests_spec: testNormal
        filters:
          branches:
            ignore: master
        requires:
          - lumigo-orb/be-deploy

  master-build:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
    - create-push-release:
        filters:
          branches:
            only:
            - master
