version: 2.1
executors:
  default:
    docker:
    - image: circleci/golang:1.17

orbs:
  github-cli: &github_cli_version circleci/github-cli@1.0
  lumigo-orb: &lumigo_orb_version lumigo/lumigo-orb@volatile

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

workflows:
  test-deploy:
    jobs:
    - lumigo-orb/print_orb_versions:
        github_cli_version: *github_cli_version
        lumigo_orb_version: *lumigo_orb_version

    - test:
        context:
          - common
          - golang

    - lumigo-orb/is_environment_available:
        context: common
        filters:
          branches:
            ignore: master
    - lumigo-orb/be-deploy:
        context: common
        requires:
          - lumigo-orb/is_environment_available
    - lumigo-orb/integration-test-prep:
        context: common
        requires:
          - lumigo-orb/be-deploy
    - lumigo-orb/integration-test-limited-flows:
        context: common
        requires:
          - lumigo-orb/integration-test-prep
    - lumigo-orb/integration-test-parallel:
        context: common
        requires:
          - lumigo-orb/integration-test-limited-flows
    - lumigo-orb/workflow-completed-successfully:
        requires:
          - test
          - lumigo-orb/integration-test-parallel

    - create-push-release:
        context:
          - common
          - golang
        filters:
          branches:
            only:
            - master
        requires:
          - test

jobs:
  test:
    executor:
      name: default
    steps:
    - checkout
    - lumigo-orb/checkout_utils
    - *restore_cache
    - run: go install golang.org/dl/go1.16@latest
    - run: go1.16 download
    - run: go install golang.org/dl/go1.18@latest
    - run: go1.18 download
    - run: export GO=go && make checks # runs test for go1.17
    - run: export GO=go1.16 && make checks
    - run: export GO=go1.18 && make checks
    - run: make upload-codecov
    - *save_cache

  create-push-release:
    executor:
      name: default
    steps:
    - github-cli/setup
    - checkout
    - lumigo-orb/checkout_utils
    - run: |
        make release
